
    <footer>
        <!-- Haut du footer -->
        <div id="entete">
            <div class="entete_haut">
                <div class="head">
                    <h1>Lose<span>1</span>Max</h1>
                    <p>N°27 des paris en ligne - Les pires côtes sur les paris sportifs</p>
                </div>

                <div class="social_media">
                    <img src="public/images/logo/instagram.png" alt="instagram">
                    <img src="public/images/logo/x.jpg" alt="x">
                    <img src="public/images/logo/facebook.png" alt="facebook">
                </div>
            </div>

            <p class="etudes">&Eacute;tudes réalisées sur trois matchs depuis hier, par nous même. On est trop fort, bref utilisez notre service. PS : le système de pari en ligne est bidon</p>
        </div>


        <div id="separation"></div>

        <!-- Bas du footer -->
        <div id="bandeau">
            <div class="partenaires">
                <h3>Partenaires Officiels (ou pas)</h3>
                <div class="container-sponsors">
                    <img src="public/images/sponsors/BallePerdue_com.png" alt="BallePerdue_com" />
                    <img src="public/images/sponsors/ChuteDirect.png" alt=" Chute Direct" />
                    <img src="public/images/sponsors/CruePari.png" alt="Crue Pari" />
                    <img src="public/images/sponsors/FcPanzani.png" alt="Fc Panzani" />
                    <img src="public/images/sponsors/StadeLavauto.png" alt="StadeLavauto" />
                    <img src="public/images/sponsors/TacleTardBis.png" alt="TacleTard" />
                </div>
            </div>
            <div class="ethique">
                <h3>Jeu éthique et sécurité</h3>
                <div class="texte-ethique">
                    <p>Les jeux d'argent et de hasard peuvent comporter des risques, tels que des pertes financières, des tensions familiales et des problèmes de dépendance.</p>
                    <p>Sur Lose1Max, on mise avant tout pour le fun, et non pour s'endetter.</p>
                    <p>Restez maître de votre jeu, fixez des limites, et ne misez jamais plus que ce que vous pouvez vous permettre de perdre.</p>
                    <p>Si vous ressentez une perte de contrôle ou si vous avez des doutes, n'hésitez pas à en parler.</p>
                    <p>Des ressources existent pour vous aider : consultez <a href="https://www.joueurs-info-service.fr" target="_blank">joueurs-info-service.fr</a></p>
                    <p>ou appelez le <a href="tel:0974751313">09 74 75 13 13</a> (appel non surtaxé).</p>
                </div>
            </div>

        </div>
        <div id="separation"></div>
        <div class="footer-fin">
            <p>© 2025 Lose1Max - Tous droits réservés</p>
        </div>
    </footer>
</body>

</html>