<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Los1max | 404</title>
    <link rel="stylesheet" href="public/css/base.css">
    <link rel="stylesheet" href="public/css/fonts.css">
    <link rel="stylesheet" href="public/css/error.css">
</head>
<body>
    <main>
        <section>
            <h1>Lose<span>1</span>Max</h1>
            <p>Error 404 : This page does not exist</p>
        </section>
    </main>
    <footer>
        <a href="index.php?page=home">Revenir à l'accueil</a>
    </footer>
</body>
</html>