    <br>
    <div class="sponsorPanneau" id="sponsorPanneau">
        <div class="sponsorLogo" id="sponsorLogo">

            <img src="public/images/sponsors/BallePerdue_com.png" alt="BallePerdue_com" />
            <img src="public/images/sponsors/ChuteDirect.png" alt=" ChuteDirect" />
            <img src="public/images/sponsors/CruePari.png" alt="CruePari" />
            <h1>Lose<span>1</span>Max</h1>
            <img src="public/images/sponsors/FcPanzani.png" alt="FcPanzani" />
            <img src="public/images/sponsors/StadeLavauto.png" alt="StadeLavauto" />
            <img src="public/images/sponsors/TacleTardBis.png" alt="TacleTardBis" />
            
            <!--Double pour boucle fluide-->
            <img src="public/images/sponsors/BallePerdue_com.png" alt="BallePerdue_com" />
            <img src="public/images/sponsors/ChuteDirect.png" alt=" ChuteDirect" />
            <img src="public/images/sponsors/CruePari.png" alt="CruePari" />
            <h1>  Lose<span>1</span>Max</h1>
            <img src="public/images/sponsors/FcPanzani.png" alt="FcPanzani" />
            <img src="public/images/sponsors/StadeLavauto.png" alt="StadeLavauto" />
            <img src="public/images/sponsors/TacleTardBis.png" alt="TacleTardBis" />
        </div>
    </div>
    <script src="public/js/sponsor.js"></script>